#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BASE_BRANCH="main"
MERGE_BASE=$(git merge-base HEAD $BASE_BRANCH)

pnpm lint-staged --relative
pnpm nx affected -t lint --fix=true --base=$MERGE_BASE
pnpm nx affected -t test --uncommitted
