name: CI
on:
  push:
    branches:
      - main

    jobs:
      main:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [ 22 ]
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Install pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 9
          - name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.node-version }}
              cache: 'pnpm'
          - name: Install dependencies
            run: pnpm install --frozen-lockfile
          - uses: nrwl/nx-set-shas@v3
          - run: pnpx nx format:check
          - run: pnpx nx affected -t lint,test,build --parallel=3
