name: CI
'on':
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set Base and Head
        run: |
          git fetch origin main
          BASE_SHA=$(git rev-parse HEAD^)
          echo "Using BASE_SHA: $BASE_SHA"
          echo "NX_BASE=$BASE_SHA" >> $GITHUB_ENV
          echo "NX_HEAD=$GITHUB_SHA" >> $GITHUB_ENV

      - name: Format Check
        run: pnpm nx format:check --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: Run affected commands
        run: pnpm nx affected -t lint,test,build --parallel=3 --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
