name: CI
on:
  pull_request: null
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CYPRESS_CACHE_FOLDER: cypress_cache
    strategy:
      matrix:
        node-version:
          - 22
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: pnpm

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: cypress_cache
          key: ${{ runner.os }}-cypress-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Cypress binary
        run: pnpm exec cypress install

      - name: Set Base and Head for PR
        run: |
          git fetch origin --prune
          git fetch origin ${{ github.base_ref }}
          BASE_SHA=$(git merge-base HEAD origin/${{ github.base_ref }})
          HEAD_SHA=$(git rev-parse HEAD)
          echo "NX_BASE=$BASE_SHA" >> $GITHUB_ENV
          echo "NX_HEAD=$HEAD_SHA" >> $GITHUB_ENV

      - name: Format Check
        run: pnpm nx format:check --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

      - name: Replace environment Variables in environment.ts
        run: |
          sed -i "s|REPLACE_SUPABASE_URL|${{ secrets.SUPABASE_URL }}|g" libs/fithelper-front/environments/util/environment.ts
          sed -i "s|REPLACE_SUPABASE_KEY|${{ secrets.SUPABASE_KEY }}|g" libs/fithelper-front/environments/util/environment.ts

      - name: Run affected commands
        env:
          PLAYWRIGHT_EMAIL: ${{ secrets.PLAYWRIGHT_EMAIL }}
          PLAYWRIGHT_PASSWORD: ${{ secrets.PLAYWRIGHT_PASSWORD }}
        run: |
          pnpm nx affected -t lint,test,build --parallel=3 --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
          pnpm nx affected -t component-test --configuration=production --parallel=3 --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
          pnpm nx affected -t e2e --configuration=production --parallel=3 --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
